Presentation/AutoSpareParts.MVC/Areas/Admin/Controllers/IpOperationController.cs
using AutoSpareParts.Application.Constants;
using AutoSpareParts.Application.CustomAttributes;
using AutoSpareParts.Application.DTOs.Common;
using AutoSpareParts.Application.Features.IpOperations.Commands.CreateIpAddressCommand;
using AutoSpareParts.Application.Features.IpOperations.Commands.SetIpAddressActiveCommand;
using AutoSpareParts.Application.Features.IpOperations.Commands.SetIpAddressPassiveCommand;
using AutoSpareParts.Application.Features.IpOperations.Commands.UpdateIpAddressCommand;
using AutoSpareParts.Application.Features.IpOperations.DTOs;
using AutoSpareParts.Application.Features.IpOperations.Queries.GetByIdIpAddressQuery;
using AutoSpareParts.Application.Features.IpOperations.Queries.GetIpAddressListQuery;
using AutoSpareParts.Domain.Enums;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Messages = AutoSpareParts.Application.Features.IpOperations.Constants.Messages;


namespace AutoSpareParts.MVC.Areas.Admin.Controllers;

[Area("Admin")]
public class IpOperationController : Controller
{
    private readonly IMediator _mediator;

    public IpOperationController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> GetAllIpAddresses(DatatableRequestDto datatableRequestDto)
    {
        var dresult = await _mediator.Send(new GetIpAddressListQueryRequest()
        {
            DatatableRequestDto = datatableRequestDto
        });

        var jsonData = new
        {
            draw = dresult.Result.Data.Draw, recordsFiltered = dresult.Result.Data.RecordsFiltered,
            recordsTotal = dresult.Result.Data.RecordsTotal, data = dresult.Result.Data.Data, isSusccess = true
        };
        return Ok(jsonData);
    }


    [HttpPost]
    [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.IpOperation, EndpointType = EndpointType.Writing,
        Definition = "Create IpAddress")]
    public async Task<IActionResult> CreateIpAddress(IpDto ipDto)
    {
        if (!ModelState.IsValid)
        {
            return PartialView("PartialViews/_IpCreateModalPartial", ipDto);
        }

        var dresult = await _mediator.Send(new CreateIpAddressCommandRequest()
        {
            IpDto = ipDto
        });
        if (dresult.Result.ResultStatus == ResultStatus.Success)
        {
            return Json(new { success = true });
        }

        return Json(new { success = false });
    }


    [HttpPost]
    [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.IpOperation, EndpointType = EndpointType.Updating,
        Definition = "Update IpAddress")]
    public async Task<IActionResult> UpdateIpAddress(IpDto ipDto)
    {
        if (!ModelState.IsValid)
        {
            return PartialView("PartialViews/_IpUpdateModalPartial", ipDto);
        }

        var dresult = await _mediator.Send(new UpdateIpAddressCommandRequest()
        {
            IpDto = ipDto
        });
        if (dresult.Result.ResultStatus == ResultStatus.Error && dresult.Result.Message.Equals(Messages.IpNotFound))
        {
            ModelState.AddModelError("IpNotFound", Messages.IpNotFound);
            return PartialView("PartialViews/_IpUpdateModalPartial", ipDto);
        }

        if (dresult.Result.ResultStatus == ResultStatus.Success)
        {
            return Json(new { success = true });
        }

        return Json(new { success = false });
    }

    [HttpPost]
    public async Task<IActionResult> SetIpAddressActive(int id)
    {
        var dresult = await _mediator.Send(new SetIpAddressActiveCommandRequest()
        {
            Id = id
        });

        if (dresult.Result.ResultStatus == ResultStatus.Success)
        {
            return Json(new { success = true });
        }

        if (dresult.Result.ResultStatus == ResultStatus.Error &&
            dresult.Result.Message.Equals(Messages.IpNotFound))
        {
            ModelState.AddModelError("IpNotFound", Messages.IpNotFound);
            var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
            return Json(new { success = false, errors = errors });
        }

        if (dresult.Result.ResultStatus == ResultStatus.Error &&
            dresult.Result.Message.Equals(Messages.IpActive))
        {
            ModelState.AddModelError("IpActive", Messages.IpActive);
            var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
            return Json(new { success = false, errors = errors });
        }

        return Json(new { success = false });
    }

    [HttpPost]
    public async Task<IActionResult> SetIpAddressPassive(int id)
    {
        var dresult = await _mediator.Send(new SetIpAddressPassiveCommandRequest()
        {
            Id = id
        });

        if (dresult.Result.ResultStatus == ResultStatus.Success)
        {
            return Json(new { success = true });
        }

        if (dresult.Result.ResultStatus == ResultStatus.Error &&
            dresult.Result.Message.Equals(Messages.IpNotFound))
        {
            ModelState.AddModelError("IpNotFound", Messages.IpNotFound);
            var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
            return Json(new { success = false, errors = errors });
        }

        if (dresult.Result.ResultStatus == ResultStatus.Error &&
            dresult.Result.Message.Equals(Messages.IpNotActive))
        {
            ModelState.AddModelError("IpNotActive", Messages.IpNotActive);
            var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
            return Json(new { success = false, errors = errors });
        }

        return Json(new { success = false });
    }

    [HttpGet]
    [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.IpOperation, EndpointType = EndpointType.Reading,
        Definition = "Get By Id IpAddress Details")]
    public async Task<IActionResult> GetIpAddressById(int id)
    {
        var dresult = await _mediator.Send(new GetByIdIpAddressQueryRequest()
        {
            Id = id
        });
        if (dresult.Result.ResultStatus == ResultStatus.Success)
        {
            return Json(new { success = true, ip = dresult.Result.Data });
        }

        if (dresult.Result.ResultStatus == ResultStatus.Error && dresult.Result.Message.Equals(Messages.IpNotFound))
        {
            ModelState.AddModelError("IpNotFound", Messages.IpNotFound);
            var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
            return Json(new { success = false, errors = errors });
        }

        return Json(new { success = false });
    }
}

Presentation/AutoSpareParts.MVC/Areas/Admin/Controllers/RoleOperationController.cs
using AutoSpareParts.Application.Constants;
using AutoSpareParts.Application.CustomAttributes;
using AutoSpareParts.Application.DTOs.Common;
using AutoSpareParts.Application.Features.RoleOperations.Commands.CreateRoleCommand;
using AutoSpareParts.Application.Features.RoleOperations.Commands.RemoveUserFromRoleCommand;
using AutoSpareParts.Application.Features.RoleOperations.Commands.SetRoleActiveCommand;
using AutoSpareParts.Application.Features.RoleOperations.Commands.SetRolePassiveCommand;
using AutoSpareParts.Application.Features.RoleOperations.Commands.UpdateRoleCommand;
using AutoSpareParts.Application.Features.RoleOperations.DTOs;
using AutoSpareParts.Application.Features.RoleOperations.Queries.GetByIdRoleQuery;
using AutoSpareParts.Application.Features.RoleOperations.Queries.GetRoleListQuery;
using AutoSpareParts.Application.Features.RoleOperations.Queries.GetUsersOfTheRoleQuery;
using AutoSpareParts.Domain.Enums;
using MediatR;
using Microsoft.AspNetCore.Mvc;


namespace AutoSpareParts.MVC.Areas.Admin.Controllers;


[Area("Admin")]
    public class RoleOperationController : Controller
    {
        private readonly IMediator _mediator;

        public RoleOperationController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.RoleOperation, EndpointType = EndpointType.Reading, Definition = "Get RoleOperation Index Page")]
        public IActionResult  Index()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> GetAllRoles(DatatableRequestDto datatableRequestDto)
        {
            
            var dresult = await _mediator.Send(new GetRoleListQueryRequest()
            {
                DatatableRequestDto = datatableRequestDto
            });

            var jsonData = new
            {
                draw = dresult.Result.Data.Draw, recordsFiltered = dresult.Result.Data.RecordsFiltered, 
                recordsTotal = dresult.Result.Data.RecordsTotal, data = dresult.Result.Data.Data, isSusccess = true
            };
            return Ok(jsonData);
        }

        [HttpGet]
        [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.RoleOperation, EndpointType = EndpointType.Reading, Definition = "Get Users Of TheRole Index Page")]
        public  async Task<IActionResult> UsersOfTheRole(int id)
        {
            var dresult = await _mediator.Send(new GetByIdRoleQueryRequest()
            {
                Id=id.ToString()
            });
            if (dresult.Result.ResultStatus == ResultStatus.Success)
            {
                return View(dresult.Result.Data);
            }
            return RedirectToAction("Index", "Error" ,new { area = "", statusCode = 400});
        }
        
        [HttpPost]
        public  async Task<IActionResult> UsersOfTheRole(DatatableRequestDto datatableRequestDto,[FromQuery]string id)
        {
            var dresult = await _mediator.Send(new GetUsersOfTheRoleQueryRequest()
            {
                Id=id,
                DatatableRequestDto = datatableRequestDto
            });

            var jsonData = new
            {
                draw = dresult.Result.Data.Draw, recordsFiltered = dresult.Result.Data.RecordsFiltered, 
                recordsTotal = dresult.Result.Data.RecordsTotal, data = dresult.Result.Data.Data, isSusccess = true
            };
            return Ok(jsonData);
        }
        
        [HttpPost]
        public  async Task<IActionResult> RemoveUserFromRole(int userId,int roleId)
        {
            var dresult = await _mediator.Send(new RemoveUserFromRoleCommandRequest()
            {
                UserId = userId.ToString(),
                RoleId = roleId.ToString()
            });

            if (dresult.Result.ResultStatus == ResultStatus.Success)
            {
                return Json(new { success = true });
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error &&
                dresult.Result.Message.Equals(Messages.UserNotFound))
            {
                ModelState.AddModelError("UserNotFound", Messages.UserNotFound);
                var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
                return Json(new { success = false, errors = errors });
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error &&
                dresult.Result.Message.Equals(Messages.UserNotActive))
            {
                ModelState.AddModelError("UserNotActive", Messages.UserNotActive);
                var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
                return Json(new { success = false, errors = errors });
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error && dresult.Result.IdentityErrorList!=null)
            {
                dresult.Result.IdentityErrorList.ForEach(e => ModelState.AddModelError(e.Code, e.Description));
                var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
                return Json(new { success = false, errors = errors });
            }
            return Json(new { success = false });
        }

        [HttpPost]
        [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.RoleOperation, EndpointType = EndpointType.Writing, Definition = "Create Role")]
        public async Task<IActionResult> CreateRole(RoleDto roleDto)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("PartialViews/_RoleCreateModalPartial", roleDto);
            }
            var dresult = await _mediator.Send(new CreateRoleCommandRequest()
            {
                RoleDto = roleDto
            });
            if (dresult.Result.ResultStatus == ResultStatus.Error && dresult.Result.IdentityErrorList!=null)
            {
                dresult.Result.IdentityErrorList.ForEach(e => ModelState.AddModelError(e.Code, e.Description));
                return PartialView("PartialViews/_RoleCreateModalPartial", roleDto);   
            }
            if (dresult.Result.ResultStatus == ResultStatus.Success)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

        [HttpPost]
        [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.RoleOperation, EndpointType = EndpointType.Updating, Definition = "Update Role")]
        public async Task<IActionResult> UpdateRole(RoleDto roleDto)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("PartialViews/_RoleUpdateModalPartial", roleDto);
            }
            var dresult = await _mediator.Send(new UpdateRoleCommandRequest()
            {
                RoleDto = roleDto
            });
            if (dresult.Result.ResultStatus == ResultStatus.Error && dresult.Result.IdentityErrorList!=null)
            {
                dresult.Result.IdentityErrorList.ForEach(e => ModelState.AddModelError(e.Code, e.Description));
                return PartialView("PartialViews/_RoleUpdateModalPartial", roleDto);   
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error && dresult.Result.Message.Equals(Messages.RoleNotFound))
            {
                ModelState.AddModelError("RoleActive", Messages.RoleNotFound);
                return PartialView("PartialViews/_RoleUpdateModalPartial", roleDto);   
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error && dresult.Result.Message.Equals(Messages.RoleDefaultRole))
            {
                ModelState.AddModelError("RoleDefaultRole", Messages.RoleDefaultRole);
                return PartialView("PartialViews/_RoleUpdateModalPartial", roleDto);   
            }
            if (dresult.Result.ResultStatus == ResultStatus.Success)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        
        [HttpPost]
        public async Task<IActionResult> SetRoleActive(int id)
        {
            var dresult = await _mediator.Send(new SetRoleActiveCommandRequest()
            {
                Id = id
            });

            if (dresult.Result.ResultStatus == ResultStatus.Success)
            {
                return Json(new { success = true });
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error &&
                dresult.Result.Message.Equals(Messages.RoleNotFound))
            {
                ModelState.AddModelError("RoleNotFound", Messages.RoleNotFound);
                var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
                return Json(new { success = false, errors = errors });
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error &&
                dresult.Result.Message.Equals(Messages.RoleDefaultRole))
            {
                ModelState.AddModelError("RoleDefaultRole", Messages.RoleDefaultRole);
                var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
                return Json(new { success = false, errors = errors });
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error &&
                dresult.Result.Message.Equals(Messages.RoleActive))
            {
                ModelState.AddModelError("RoleActive", Messages.RoleActive);
                var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);
                return Json(new { success = false, errors = errors });
            }
            if (dresult.Result.ResultStatus == ResultStatus.Error && dresult.Result.IdentityErrorList!=null)
            {
                dresult.Result.IdentityErrorList.ForEach(e => ModelState.AddModelError(e.Code, e.Description));
                var errors = ModelState.ToDictionary(x => x.Key, x => x.Value?.Errors);

Presentation/AutoSpareParts.MVC/Areas/Admin/Views/Shared/Admin/_AdminHeader.cshtml
<header id="header" class="header">
    <div class="header-menu">
        <div class="col-sm-7">
            <a id="menuToggle" class="menutoggle pull-left">
                <i class="fa fa fa-tasks"></i>
            </a>
            <div class="header-left">
                <button class="search-trigger">
                    <i class="fa fa-search"></i>
                </button>
                <div class="form-inline">
                    <form class="search-form">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-close" type="submit">
                            <i class="fa fa-close"></i>
                        </button>
                    </form>
                </div>

                <div class="dropdown for-notification">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="count bg-danger">5</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="notification">
                        <p class="red">You have 3 Notification</p>
                        <a class="dropdown-item media bg-flat-color-1" href="#">
                            <i class="fa fa-check"></i>
                            <p>Server #1 overloaded.</p>
                        </a>
                        <a class="dropdown-item media bg-flat-color-4" href="#">
                            <i class="fa fa-info"></i>
                            <p>Server #2 overloaded.</p>
                        </a>
                        <a class="dropdown-item media bg-flat-color-5" href="#">
                            <i class="fa fa-warning"></i>
                            <p>Server #3 overloaded.</p>
                        </a>
                    </div>
                </div>

                <div class="dropdown for-message">
                    <button class="btn btn-secondary dropdown-toggle" type="button"
                            id="message"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="ti-email"></i>
                        <span class="count bg-primary">9</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="message">
                        <p class="red">You have 4 Mails</p>
                        <a class="dropdown-item media bg-flat-color-1" href="#">
                            <span class="photo media-left">
                                <img alt="avatar" src="~/admin/images/avatar/1.jpg">
                            </span>
                            <span class="message media-body">
                                <span class="name float-left">Jonathan Smith</span>
                                <span class="time float-right">Just now</span>
                                <p>Hello, this is an example msg</p>
                            </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-4" href="#">
                            <span class="photo media-left">
                                <img alt="avatar" src="~/admin/images/avatar/2.jpg">
                            </span>
                            <span class="message media-body">
                                <span class="name float-left">Jack Sanders</span>
                                <span class="time float-right">5 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-5" href="#">
                            <span class="photo media-left">
                                <img alt="avatar" src="~/admin/images/avatar/3.jpg">
                            </span>
                            <span class="message media-body">
                                <span class="name float-left">Cheryl Wheeler</span>
                                <span class="time float-right">10 minutes ago</span>
                                <p>Hello, this is an example msg</p>
                            </span>
                        </a>
                        <a class="dropdown-item media bg-flat-color-3" href="#">
                            <span class="photo media-left">
                                <img alt="avatar" src="~/admin/images/avatar/4.jpg">
                            </span>
                            <span class="message media-body">
                                <span class="name float-left">Rachel Santos</span>
                                <span class="time float-right">15 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-5">
                    <!-- AdminHeader Avatar-->
                    @await Component.InvokeAsync("AdminHeaderAvatar")
                    <!-- AdminHeader Avatar-->
                    <div class="language-select dropdown" id="language-select">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="language" aria-haspopup="true" aria-expanded="true">
                    <i class="flag-icon flag-icon-tr"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="language">
                    <div class="dropdown-item">
                        <span class="flag-icon flag-icon-fr"></span>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-es"></i>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-us"></i>
                    </div>
                    <div class="dropdown-item">
                        <i class="flag-icon flag-icon-it"></i>
                    </div>
                </div>
            </div>

        </div>
    </div>

</header><!-- /header -->

Presentation/AutoSpareParts.MVC/Areas/Admin/Views/Shared/Admin/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <meta name="keywords" content="Auto-Spear-Parts" />
    <meta name="description" content="Auto-Spear-Parts">
    <meta name="author" content="Auto-Spear-Parts">
    <title>@ViewData["Title"] - AdminPanel</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="~/icons/favicon.png">
    <!-- Css Styles -->
    <link rel="stylesheet" href="~/lib/bootstrap4/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/admin/fonts/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/icons/themify-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/icons/flag-icon/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/admin/css/admin.css" asp-append-version="true"/>

    <link rel="stylesheet" href="~/admin/fonts/googlefonts/css/googlefonts.css">
    @await RenderSectionAsync("Style", required: false)

</head>

<body>
<!-- Left Panel -->
<partial name="Admin/_AdminLeftPanel"/>
<!-- Left Panel -->

<!-- Right Panel -->
<aside id="right-panel" class="right-panel">

    <!-- Header-->
    <partial name="Admin/_AdminHeader"/>
    <!-- Header-->

    @RenderBody()

</aside><!-- /#right-panel -->
<!-- Right Panel -->
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap4/dist/js/bootstrap.bundle.min.js"></script>
@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
<script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
<script src="~/admin/js/admin.js" asp-append-version="true"></script>
<script src="~/admin/js/adminlayout/adminlayout.js" asp-append-version="true"></script>
<script src="~/js/common/alllayouts.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Presentation/AutoSpareParts.MVC/Areas/Admin/Views/Shared/Admin/_AdminLeftPanel.cshtml
<aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
    
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                 <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img src="~/admin/images/logo.png" alt="Logo">
                </a>
                <a class="navbar-brand hidden" href="./">
                    <img src="~/admin/images/logo2.png" alt="Logo">
                </a>
            </div>
    
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index"><i class="menu-icon fa fa-dashboard"></i>Dashboard</a>
                    </li>
                    <h3 class="menu-title">UI elements</h3><!-- /.menu-title -->
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-users"></i>Kullanıcı Yönetimi</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li>
                                <i class="fa fa-user"></i><a asp-area="Admin" asp-controller="UserOperation"  asp-action="Index"  class="nav-link" >Aktif Kullanıcılar</a>
                            </li>
                            <li>
                                <i class="fa fa-ban"></i><a asp-area="Admin" asp-controller="DeletedAccount"  asp-action="Index"  class="nav-link" >Silinmiş Kullanıcılar</a>
                            </li>
                            <li>
                                <i class="fa fa-cogs"></i><a asp-area="Admin" asp-controller="RoleOperation"  asp-action="Index" class="nav-link" >Rol İşlemleri</a>
                            </li>
                            <li>
                                <i class="fa fa-cogs"></i><a asp-area="Admin" asp-controller="IpOperation"  asp-action="Index" class="nav-link" >IP İşlemleri</a>
                            </li>
                            <li>
                                <i class="fa fa-toggle-on"></i><a asp-area="Admin" asp-controller="AuthorizeEndpoint"  asp-action="Index" class="nav-link" >Rol Bazlı Endpoint Yetkilendirme İşlemleri</a>
                            </li>
                            <li>
                                <i class="fa fa-toggle-off"></i><a asp-area="Admin" asp-controller="AuthorizeEndpoint"  asp-action="AuthorizeEndpoints" class="nav-link" >Ip Bazlı Endpoint Yetkilendirme İşlemleri</a>
                            </li>
                        </ul>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Tables</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li>
                                <i class="fa fa-table"></i><a href="#">Basic Table</a>
                            </li>
                            <li>
                                <i class="fa fa-table"></i><a href="#">Data Table</a>
                            </li>
                        </ul>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-th"></i>Forms</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li>
                                <i class="menu-icon fa fa-th"></i><a href="#">Basic Form</a>
                            </li>
                            <li>
                                <i class="menu-icon fa fa-th"></i><a href="#">Advanced Form</a>
                            </li>
                        </ul>
                    </li>
    
                    <h3 class="menu-title">Icons</h3><!-- /.menu-title -->
    
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-tasks"></i>Icons</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li>
                                <i class="menu-icon fa fa-fort-awesome"></i><a href="#">Font Awesome</a>
                            </li>
                            <li>
                                <i class="menu-icon ti-themify-logo"></i><a href="#">Themefy Icons</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"> <i class="menu-icon fa fa-th"></i>Widgets </a>
                    </li>

                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-area-chart"></i>Maps</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li>
                                <i class="menu-icon fa fa-map-o"></i><a href="#">Google Maps</a>
                            </li>
                            <li>
                                <i class="menu-icon fa fa-street-view"></i><a href="#">Vector Maps</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside><!-- /#left-panel -->