Presentation/AutoSpareParts.MVC/Areas/Admin/Controllers/UserImageController.cs
using AutoSpareParts.Application.Constants;
using AutoSpareParts.Application.CustomAttributes;
using AutoSpareParts.Application.Features.UserImages.Commands.CreateUserImageCommand;
using AutoSpareParts.Application.Features.UserImages.Commands.DeleteUserImageCommand;
using AutoSpareParts.Application.Features.UserImages.Commands.SetProfilImageCommand;
using AutoSpareParts.Application.Features.UserImages.DTOs;
using AutoSpareParts.Domain.Enums;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Messages = AutoSpareParts.Application.Features.UserImages.Constants.Messages;

namespace AutoSpareParts.MVC.Areas.Admin.Controllers;

[Area("Admin")]
public class UserImageController : Controller
{
    private readonly IMediator _mediator;

    public UserImageController(IMediator mediator)
    {
        _mediator = mediator;
    }
    
    [HttpGet]
    [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.UserImage, EndpointType = EndpointType.Reading, Definition = "Get By Id User for Create UserImage")]
    public IActionResult CreateUserImage(int userId)
    {
        CreateUserImageDto createUserImageDto = new CreateUserImageDto();
        createUserImageDto.UserId = userId;
        return View(createUserImageDto);
    }
    
    [HttpPost]
    [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.UserImage, EndpointType = EndpointType.Writing, Definition = "Create UserImage")]
    public async Task<IActionResult> CreateUserImage(CreateUserImageDto createUserImageDto)
    {
        if (ModelState.IsValid)
        {
            var dresult = await _mediator.Send(new CreateUserImageCommandRequest
            {
                UserImageAddDto = createUserImageDto, 
                CreatedByName = User.Identity?.Name
            });
            if (dresult.Result.Message == Messages.UserImageCountMoreThan4)
            { 
                ModelState.AddModelError("UserImageCountMoreThan4", Messages.UserImageCountMoreThan4);
                return View(createUserImageDto);
            }
            if (dresult.Result.ResultStatus == ResultStatus.Success)
            {
                TempData["CreateUserImageSuccess"] = true;
                return RedirectToAction("createUserImage", "UserImage" ,new { area = "Admin" ,userId=createUserImageDto.UserId});
            }
        }
        return View(createUserImageDto);
    }
    [HttpPost]
    public async Task<IActionResult> SetProfilImage(int id,int userId)
    {
        if (id>0)
        {
            var dresult = await _mediator.Send(new SetProfilImageCommandRequest
            {
                Id = id,
                UserId = userId,
                ModifiedByName = User.Identity?.Name
            });
            if (dresult.Result.ResultStatus==ResultStatus.Success)
            {
                return Json(new { success = true});
            }
            return Json(new { success = false});
        }
        return RedirectToAction("Index", "Error" ,new { area = "", statusCode = 400});
    }
    
        
    [HttpPost]
    [AuthorizeEndpoint(Menu = AuthorizeEndpointConstants.UserImage, EndpointType = EndpointType.Deleting, Definition = "Delete UserImage")]
    public async Task<IActionResult> DeleteUserImage(int id)
    {
        if (id > 0)
        {
            var dresult = await _mediator.Send(new DeleteUserImageCommandRequest
            {
                Id = id, 
                ModifiedByName = User.Identity?.Name
            });
            if (dresult.Result.ResultStatus==ResultStatus.Success)
            {
                return Json(new { success = true});
            }
            return Json(new { success = false});
        }
        return RedirectToAction("Index", "Error" ,new { area = "", statusCode = 400});
    }
}

Presentation/AutoSpareParts.MVC/Areas/Admin/ViewComponents/UserImageCardViewComponent.cs
using AutoSpareParts.Application.Features.UserImages.Queries.GetByUserIdAllUserImageQuery;
using AutoSpareParts.Domain.Enums;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace AutoSpareParts.MVC.Areas.Admin.ViewComponents;

[ViewComponent]
public class UserImageCardViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;

        public UserImageCardViewComponent(IMediator mediator)
        {
             _mediator = mediator;
        }

        public async Task<IViewComponentResult> InvokeAsync(int userId)
        {
            if (userId > 0)
            {
                var dresult = await _mediator.Send(new GetByUserIdAllUserImageQueryRequest()
                {
                    UserId = userId,
                });
                if (dresult.Result.ResultStatus == ResultStatus.Success)
                {
                    ViewBag.UserId = userId;
                    return View(dresult.Result.Data.OrderBy(i=>i.Id).ToList());
                }
            }
            return View();
        }
    }

Presentation/AutoSpareParts.MVC/Areas/Admin/ViewComponents/UserSummaryCardViewComponent.cs
using AutoSpareParts.Application.Features.Accounts.Queries.GetByIdForUserSummaryCardQuery;
using AutoSpareParts.Application.Features.UserImages.Queries.GetByUserIdAllUserImageQuery;
using AutoSpareParts.Application.Features.UserImages.Queries.GetByUserIdProfilImageQuery;
using AutoSpareParts.Application.Features.UserImages.Queries.GetByUserIdUserImageCountQuery;
using AutoSpareParts.Domain.Enums;
using MediatR;
using Microsoft.AspNetCore.Mvc;


namespace AutoSpareParts.MVC.Areas.Admin.ViewComponents;

[ViewComponent]
public class UserSummaryCardViewComponent : ViewComponent
{

    private readonly IMediator _mediator;

    public UserSummaryCardViewComponent(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IViewComponentResult> InvokeAsync(int userId)
    {
        var countResult = await _mediator.Send(new GetByUserIdUserImageCountQueryRequest()
        {
            UserId = userId
        });
        if (countResult.Result.ResultStatus == ResultStatus.Success)
            ViewBag.UserImageCount = countResult.Result.Data;
        
        var profilResult = await _mediator.Send(new GetByUserIdProfilImageQueryRequest()
        {
            UserId = userId
        });
        if (profilResult.Result.ResultStatus == ResultStatus.Success)
        {
            if (profilResult.Result.Data != null)
                ViewBag.UserImageProfilImagePath = profilResult.Result.Data.Path;

            if (countResult.Result.Data > 0)
            {
                var allImageResult = await _mediator.Send(new GetByUserIdAllUserImageQueryRequest()
                {
                    UserId = userId
                });
                if (allImageResult.Result.ResultStatus == ResultStatus.Success)
                {
                    ViewBag.UserImageList = allImageResult.Result.Data;
                }
            }
        }
        else
        {
            if (countResult.Result.Data > 0)
            {
                var allImageResult = await _mediator.Send(new GetByUserIdAllUserImageQueryRequest()
                {
                    UserId = userId
                });
                if (allImageResult.Result.ResultStatus == ResultStatus.Success)
                {
                    ViewBag.UserImageList = allImageResult.Result.Data;
                }
            }
        }
        var userCardSummaryResult = await _mediator.Send(new GetByIdForUserSummaryCardQueryRequest()
        {
            Id = userId
        });
        return View(userCardSummaryResult.Result.Data);
    }
}

Presentation/AutoSpareParts.MVC/Areas/Admin/Views/UserImage/CreateUserImage.cshtml
@model CreateUserImageDto
@{
    Layout = "Admin/_AdminLayout";
    ViewBag.Title = "Resim Ekle";
}
@section Style {
    <style>
      /*------------------------------------------------------------------
         Fancybox Gallery Section   
      -------------------------------------------------------------------*/
      
      .gallery_section_inner .column {
          background: #fff;
          box-shadow: 0 0 13px -10px #000;
          overflow: hidden;
      }
      
      .heading_section {
          border-top: solid #1ed085 2px;
          background: #15283c;
      }
      
      .heading_section h4 {
          color: #fff;
          margin: 0;
          font-weight: 200;
          text-align: center;
          padding: 16px 0 16px;
          font-size: 15px;
      }
   </style>
   <link href="~/lib/fancybox/css/jquery.fancybox.css" rel="stylesheet" />
}

<div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">
                <div class="page-title">
                    <h1>Dashboard</h1>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li class="active">Dashboard</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
<div class="content mt-3">
        <div class="col-sm-12">
            <div class="alert  alert-success alert-dismissible fade show" role="alert">
                <span class="badge badge-pill badge-success">Success</span> You successfully read this important alert message.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
                <div class="container-fluid py-5" style="background-color: #eee;">
                        <div class="row">
                            <div class="col-lg-4">
                                <!-- User Card Summary-->
                                @await Component.InvokeAsync("UserSummaryCard",new { userId=Model.UserId })
                                <!-- User Card Summary-->
                                <!-- UserImage Card-->
                                @await Component.InvokeAsync("UserImageCard",new { userId=Model.UserId })
                                <!-- UserImage Card-->
                            </div>
                            <div class="col-lg-8">
                                <div class="card">
                                    <div class="card-header">
                                        <h2>Resim Ekle</h2>
                                    </div>
                                    <div class="card-body">
                                        <form asp-area="Admin" asp-controller="UserImage" asp-action="CreateUserImage" method="post" enctype="multipart/form-data">
                                            <div class="form-group row offset-3 col-9 text-danger" asp-validation-summary="All">
                                            </div>
                                            <div class="form-group row">
                                                <label asp-for="Title" class="col-sm-3 col-form-label"></label>
                                                <div class="col-sm-9">
                                                    <input asp-for="Title" class="form-control"/>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label asp-for="AltText" class="col-sm-3 col-form-label"></label>
                                                <div class="col-sm-9">
                                                    <input asp-for="AltText" class="form-control"/>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label asp-for="Note" class="col-sm-3 col-form-label"></label>
                                                <div class="col-sm-9">
                                                    <textarea asp-for="Note" class="form-control"></textarea>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label asp-for="ImageFile" class="col-sm-3 col-form-label"></label>
                                                <div class="col-sm-9">
                                                    <input asp-for="ImageFile" accept="image/*"/>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label asp-for="Profil" class="col-3 col-form-label"></label>
                                                <div class="col-9">
                                                    <input asp-for="Profil" class="mt-2"/>
                                                </div>
                                            </div>
                                            <input type="hidden" asp-for="UserId" class="form-control"/>
                                            <div class="form-group row">
                                                <div class="offset-sm-3 col-sm-9">
                                                    <input type="submit" value="Kaydet" class="btn btn-primary btn-sm"/>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
    </div> <!-- .content -->

@section Scripts {
    <script src="~/lib/fancybox/js/jquery.fancybox.min.js"></script>
    <script asp-append-version="true">
        var app = app || {};
        app.Urls = app.Urls || {};
        app.ToastMessages = app.ToastMessages || {};
        app.ToastMessages.createUserImageMessage = '@TempData["CreateUserImageSuccess"]';
    </script>
    <script src="~/admin/js/userimage/userimage.js" asp-append-version="true"></script>
}

Presentation/AutoSpareParts.MVC/Areas/Admin/Views/UserImage/Index.cshtml
@model UserImageDto

@{
    Layout = "Admin/_AdminLayout";
    ViewBag.Title = "Kullanıcı Resmi";
}

<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li class="active">Dashboard</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content mt-3">
    <div class="col-sm-12">
        <div class="alert  alert-success alert-dismissible fade show" role="alert">
            <span class="badge badge-pill badge-success">Success</span> You successfully read this important alert message.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>

    <div class="container py-5">
        UserImage index
    </div>
</div> <!-- .content -->